name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # Use the latest stable version of setup-ruby action
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      # - name: Set up database schema
      #   run: bin/rails db:schema:load
      # Run RSpec tests
      - name: Install packages
        run: bundle install
      - name: Set execute permissions for bin/rails
        run: chmod +x bin/rails
      - name: Setting Rails Environment
        run: bin/rails db:create db:migrate RAILS_ENV=test
      - name: Run RSpec tests
        run: bundle exec rake spec
      # Run Cucumber tests
      - name: Run Cucumber tests
        run: bundle exec rake cucumber
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: bundle exec coveralls push

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@v1 # Use the latest stable version of setup-ruby action
  #       with:
  #         bundler-cache: true
  #     - name: Install bundler-audit gem
  #       run: gem install bundler-audit
  #     - name: Security audit dependencies
  #       run: bundle exec bundler-audit --update
  #     - name: Security audit application code
  #       run: bundle exec brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bundle exec rubocop --parallel
